//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.08 at 09:06:03 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.arkisto.fi/skeemat/Sahke2/2011/12/20", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package lupapalvelu.tiedonohjaus;
