//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.08 at 09:06:03 PM EEST 
//


package lupapalvelu.tiedonohjaus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassificationSchemeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassificationSchemeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.arkisto.fi/skeemat/Sahke2/2011/12/20}MainFunction"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassificationSchemeType", propOrder = {
    "mainFunction"
})
public class ClassificationSchemeType {

    @XmlElement(name = "MainFunction", required = true)
    protected MainFunctionType mainFunction;

    /**
     * Gets the value of the mainFunction property.
     * 
     * @return
     *     possible object is
     *     {@link MainFunctionType }
     *     
     */
    public MainFunctionType getMainFunction() {
        return mainFunction;
    }

    /**
     * Sets the value of the mainFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link MainFunctionType }
     *     
     */
    public void setMainFunction(MainFunctionType value) {
        this.mainFunction = value;
    }

}
