//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.08 at 09:06:03 PM EEST 
//


package lupapalvelu.tiedonohjaus;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "actionEvents"
})
@XmlRootElement(name = "Custom")
public class Custom {

    @XmlElement(name = "ActionEvent")
    protected List<ActionEvent> actionEvents;

    public List<ActionEvent> getActionEvents() {
        if (actionEvents == null) {
            actionEvents = new ArrayList<ActionEvent>();
        }
        return this.actionEvents;
    }

}
