(ns sade.email-test
  (:require [sade.email :refer :all]
            [midje.sweet :refer :all]
            [postal.core :as postal]))

(facts "Facts about sending emails"
  (send-mail ...from... ...to... ...subject... nil nil) => (throws AssertionError)
  (send-mail ...from... ...to... ...subject... "plain text" nil) => nil
    (provided (postal/send-message irrelevant (contains {:from ...from...
                                                         :to ...to...
                                                         :subject ...subject...
                                                         :body [{:type "text/plain; charset=utf-8"
                                                                 :content "plain text"}]})) => nil)
  (send-mail ...from... ...to... ...subject... nil "html text") => nil
    (provided (postal/send-message irrelevant (contains {:from ...from...
                                                         :to ...to...
                                                         :subject ...subject...
                                                         :body [{:type "text/html; charset=utf-8"
                                                                 :content "html text"}]})) => nil)
  (send-mail ...from... ...to... ...subject... "plain text" "html text") => nil
    (provided (postal/send-message irrelevant (contains {:from ...from...
                                                         :to ...to...
                                                         :subject ...subject...
                                                         :body [:alternative
                                                                {:type "text/plain; charset=utf-8"
                                                                 :content "plain text"}
                                                                {:type "text/html; charset=utf-8"
                                                                 :content "html text"}]})) => nil)
  (send-mail ...from... ...to... ...subject... "plain text" "html text") => {:error "oh noes"}
    (provided (postal/send-message irrelevant (contains {:from ...from...
                                                         :to ...to...
                                                         :subject ...subject...
                                                         :body [:alternative
                                                                {:type "text/plain; charset=utf-8"
                                                                 :content "plain text"}
                                                                {:type "text/html; charset=utf-8"
                                                                 :content "html text"}]})) => {:error "oh noes"}))

