(ns lupapalvelu.user-enums)

(def koulutusvalinta
  ["arkkitehti"
   "arkkitehtiylioppilas"
   "diplomi-insin\u00f6\u00f6ri"
   "insin\u00f6\u00f6ri"
   "IV-asentaja"
   "kirvesmies"
   "LV-asentaja"
   "LVI-asentaja"
   "LVI-insin\u00f6\u00f6ri"
   "LVI-teknikko"
   "LVI-ty\u00f6teknikko"
   "maisema-arkkitehti"
   "rakennusammattity\u00f6mies"
   "rakennusarkkitehti"
   "rakennusinsin\u00f6\u00f6ri"
   "rakennusmestari"
   "rakennuspiirt\u00e4j\u00e4"
   "rakennusteknikko"
   "rakennusty\u00f6teknikko"
   "sisustusarkkitehti"
   "talonrakennusinsin\u00f6\u00f6ri"
   "talonrakennusteknikko"
   "tekniikan kandidaatti"
   "teknikko"])

(def fise-kelpoisuus-lajit
  ["tavanomainen p\u00e4\u00e4suunnittelu (uudisrakentaminen)"
   "tavanomainen p\u00e4\u00e4suunnittelu (korjausrakentaminen)"
   "vaativa p\u00e4\u00e4suunnittelu (uudisrakentaminen)"
   "vaativa p\u00e4\u00e4suunnittelu (korjausrakentaminen)"
   "poikkeuksellisen vaativa p\u00e4\u00e4suunnittelu (uudisrakentaminen)"
   "poikkeuksellisen vaativa p\u00e4\u00e4suunnittelu (korjausrakentaminen)"
   "tavanomainen rakennussuunnittelu (uudisrakentaminen)"
   "tavanomainen rakennussuunnittelu (korjausrakentaminen)"
   "vaativa rakennussuunnittelu (uudisrakentaminen)"
   "vaativa rakennussuunnittelu (korjausrakentaminen)"
   "poikkeuksellisen vaativa rakennussuunnittelu (uudisrakentaminen)"
   "poikkeuksellisen vaativa rakennussuunnittelu (korjausrakentaminen)"
   "tavanomainen betonirakenteiden suunnittelu (uudisrakentaminen)"
   "tavanomainen betonirakenteiden suunnittelu (korjausrakentaminen)"
   "vaativa betonirakenteiden suunnittelu (uudisrakentaminen)"
   "vaativa betonirakenteiden suunnittelu (korjausrakentaminen)"
   "poikkeuksellisen vaativa betonirakenteiden suunnittelu (uudisrakentaminen)"
   "poikkeuksellisen vaativa betonirakenteiden suunnittelu (korjausrakentaminen)"
   "tavanomainen puurakenteiden suunnittelu (uudisrakentaminen)"
   "tavanomainen puurakenteiden suunnittelu (korjausrakentaminen)"
   "vaativa puurakenteiden suunnittelu (uudisrakentaminen)"
   "vaativa puurakenteiden suunnittelu (korjausrakentaminen)"
   "poikkeuksellisen vaativa puurakenteiden suunnittelu (uudisrakentaminen)"
   "poikkeuksellisen vaativa puurakenteiden suunnittelu (korjausrakentaminen)"
   "tavanomainen ter\u00e4srakenteiden suunnittelu (uudisrakentaminen)"
   "tavanomainen ter\u00e4srakenteiden suunnittelu (korjausrakentaminen)"
   "vaativa ter\u00e4srakenteiden suunnittelu (uudisrakentaminen)"
   "vaativa ter\u00e4srakenteiden suunnittelu (korjausrakentaminen)"
   "poikkeuksellisen vaativa ter\u00e4srakenteiden suunnittelu (uudisrakentaminen)"
   "poikkeuksellisen vaativa ter\u00e4srakenteiden suunnittelu (korjausrakentaminen)"
   "tavanomainen pohjarakenteiden suunnittelu (uudisrakentaminen)"
   "tavanomainen pohjarakenteiden suunnittelu (korjausrakentaminen)"
   "vaativa pohjarakenteiden suunnittelu (uudisrakentaminen)"
   "vaativa pohjarakenteiden suunnittelu (korjausrakentaminen)"
   "poikkeuksellisen vaativa pohjarakenteiden suunnittelu (uudisrakentaminen)"
   "poikkeuksellisen vaativa pohjarakenteiden suunnittelu (korjausrakentaminen)"
   "tavanomainen ilmanvaihtosuunnittelu (uudisrakentaminen)"
   "tavanomainen ilmanvaihtosuunnittelu (korjausrakentaminen)"
   "vaativa ilmanvaihtosuunnittelu (uudisrakentaminen)"
   "vaativa ilmanvaihtosuunnittelu (korjausrakentaminen)"
   "poikkeuksellisen vaativa ilmanvaihtosuunnittelu (uudisrakentaminen)"
   "poikkeuksellisen vaativa ilmanvaihtosuunnittelu (korjausrakentaminen)"
   "tavanomainen kiinteist\u00f6n vesi- ja viem\u00e4rilaitteiston suunnittelu (uudisrakentaminen)"
   "tavanomainen kiinteist\u00f6n vesi- ja viem\u00e4rilaitteiston suunnittelu (korjausrakentaminen)"
   "vaativa kiinteist\u00f6n vesi- ja viem\u00e4rilaitteiston suunnittelu (uudisrakentaminen)"
   "vaativa kiinteist\u00f6n vesi- ja viem\u00e4rilaitteiston suunnittelu (korjausrakentaminen)"
   "poikkeuksellisen vaativa kiinteist\u00f6n vesi- ja viem\u00e4rilaitteiston suunnittelu (uudisrakentaminen)"
   "poikkeuksellisen vaativa kiinteist\u00f6n vesi- ja viem\u00e4rilaitteiston suunnittelu (korjausrakentaminen)"
   "tavanomainen rakennusfysikaalinen suunnittelu (uudisrakentaminen)"
   "tavanomainen rakennusfysikaalinen suunnittelu (korjausrakentaminen)"
   "vaativa rakennusfysikaalinen suunnittelu (uudisrakentaminen)"
   "vaativa rakennusfysikaalinen suunnittelu (korjausrakentaminen)"
   "poikkeuksellisen vaativa rakennusfysikaalinen suunnittelu (uudisrakentaminen)"
   "poikkeuksellisen vaativa rakennusfysikaalinen suunnittelu (korjausrakentaminen)"
   "tavanomainen akustiikkasuunnittelu (uudisrakentaminen)"
   "tavanomainen akustiikkasuunnittelu (korjausrakentaminen)"
   "vaativa akustiikkasuunnittelu (uudisrakentaminen)"
   "vaativa akustiikkasuunnittelu (korjausrakentaminen)"
   "poikkeuksellisen vaativa akustiikkasuunnittelu (uudisrakentaminen)"
   "poikkeuksellisen vaativa akustiikkasuunnittelu (korjausrakentaminen)"
   "tavanomainen kosteusvaurion korjaussuunnittelu"
   "vaativa kosteusvaurion korjaussuunnittelu"
   "poikkeuksellisen vaativa kosteusvaurion korjaussuunnittelu"])
